chars = set(input())
if "M" not in chars: print("NO"); quit()
if "O" not in chars: print("NO"); quit()
if "B" not in chars: print("NO"); quit()
if "I" not in chars: print("NO"); quit()
if "S" not in chars: print("NO"); quit()
print("YES")